### ISSUE TITLE
Issues upgrading to 3.x

### ISSUE THREAD

**Issue by gregf** [Bluewind/filebin#21]
I followed the instructions about manually updated my config files after the git pull, but I'm getting the following error now when I try to load the page.

```
2017/12/02 19:29:10 [error] 1525#1525: *27187 FastCGI sent in stderr: "PHP message: Exception 1/1 'ParseError' with message 'syntax error, unexpected end of file' in /home/filebin/www/filebin/application/config/config-local.php:25
Backtrace:
#0 /home/filebin/www/filebin/system/core/Common.php(249): require()
#1 /home/filebin/www/filebin/system/core/Common.php(300): get_config()
#2 /home/filebin/www/filebin/system/core/CodeIgniter.php(168): config_item('composer_autoload')
#3 /home/filebin/www/filebin/public_html/index.php(372): require_once('/home/filebin/www/filebin/system/core/CodeIgniter.php')
#4 /home/filebin/www/filebin/index.php(10): include('/home/filebin/www/filebin/public_html/index.php')" while reading response header from upstream, client: 64.39.95.17, server: www.filebin.pw, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/filebin-fpm.sock:", host: "filebin.pw"
```

**Comment by gregf** [comment]
Turned out to just be a missing semi colon in my config-local.php. Thanks anyways.
